revision: 3
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"


pull_request:

  converted_to_draft: ready_for_review

  ready_for_review:

    - predefined: section1

    - assignee-add: ["adegeo", "thraka"]
    - reviewer-add: "team:adegeo"

issues: 

  closed:

    # Issue closed, remove in-progress and not triaged labels
    - labels-remove: ["in-progress", ":watch: Not Triaged"]

    # Check if the issue was closed by the user who opened it
    - check:
        - type: query
          value: "Issue.user.id == Issue.closed_by.id"
      pass:
        - labels-add: ["resolved-by-customer"]

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]

    - check:
        - type: query
          value: "contains(Issue.body, '- [x] Binary incompatible') == `true`"
      pass:
        - labels-add: ["binary incompatible"]

    - check:
        - type: query
          value: "contains(Issue.body, '- [x] Source incompatible') == `true`"
      pass:
        - labels-add: ["source incompatible"]

    # default for doc comment
    - check:
        - type: metadata-exists
      pass:
        - labels-add: ["Source - Docs.ms"]

        - check:
            - type: metadata-comment
              name: issue type
              value: "(?i)breaking-change$"
          pass:
            - labels-add: ["breaking-change", "doc-idea"]
            - projects-add: [2]

        # Checks for specific paths
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/blazor.*"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/host-and-deploy\/blazor.*"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/mvc\/views\/tag-helpers\/built-in\/component-tag-helper.md"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/security\/blazor.*"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/tutorials\/*blazor*.*"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/grpc.*"
          pass:
            - labels-add: ["gRPC"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/tutorials\/grpc*.*"
          pass:
            - labels-add: ["gRPC"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/signalr.*"
          pass:
            - labels-add: ["SignalR"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/tutorials\/signalr*.*"
          pass:
            - labels-add: ["SignalR"]

predefined:

  section1:
    - variable-set:
      name: IsReaady
      value: "true"

    - check:
        - type: variable
          name: IsReady
          value: true

      pass:
        - comment: |
            ### Heading
            
            * Bullet
            * Points
